# Định nghĩa Kubernetes Job để chạy worker

apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-1
spec:
  ttlSecondsAfterFinished: 3600   # 3600 giây = giữ lại Pod trong 1 tiếng sau khi xong
  completions: 8
  parallelism: 2
  template:
    metadata:
      name: job-wq-1
    spec:
      containers:
      - name: c
        image: docker.io/huong1906/job-wq-1
        env:
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: QUEUE
          value: job1
      restartPolicy: OnFailure
