# Định nghĩa ReplicationController để chạy RabbitMQ

# rabbitmq-controller.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1 # Đảm bảo có 1 bản sao (Pod) RabbitMQ chạy
  template:
    metadata:
      labels:
        # Các label này phải khớp với selector của Service ở trên
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq # Sử dụng image RabbitMQ chính thức từ Docker Hub
        name: rabbitmq
        ports:
        - containerPort: 5672 # Port mà container RabbitMQ lắng nghe
        resources:
          limits:
            cpu: 100m # Giới hạn tài nguyên CPU (ví dụ)
